/*
###############################################################
#  Generated by:      Cadence Innovus 21.14-e032_1
#  OS:                Linux x86_64(Host ID scee173709)
#  Generated on:      Thu Dec 15 22:52:32 2022
#  Design:            ARAMB_RISCV_180_SOC
#  Command:           write_netlist fullNetlist.v
###############################################################
*/
module ARAMB_RISCV_180_SOC (
	pwrup_rst_n, 
	rst_n, 
	cpu_rst_n, 
	test_mode, 
	test_rst_n, 
	clk, 
	rtc_clk, 
	ext_irq, 
	soft_irq, 
	imem_hprot, 
	imem_hburst, 
	imem_hsize, 
	imem_htrans, 
	imem_hmastlock, 
	imem_haddr, 
	imem_hready, 
	imem_hrdata, 
	imem_hresp, 
	dmem_hprot, 
	dmem_hburst, 
	dmem_hsize, 
	dmem_htrans, 
	dmem_hmastlock, 
	dmem_haddr, 
	dmem_hwrite, 
	dmem_hwdata, 
	dmem_hready, 
	dmem_hrdata, 
	dmem_hresp);
   input pwrup_rst_n;
   input rst_n;
   input cpu_rst_n;
   input test_mode;
   input test_rst_n;
   input clk;
   input rtc_clk;
   output ext_irq;
   output soft_irq;
   output [3:0] imem_hprot;
   output [2:0] imem_hburst;
   output [2:0] imem_hsize;
   output [1:0] imem_htrans;
   output imem_hmastlock;
   output [31:0] imem_haddr;
   input imem_hready;
   input [31:0] imem_hrdata;
   input imem_hresp;
   output [3:0] dmem_hprot;
   output [2:0] dmem_hburst;
   output [2:0] dmem_hsize;
   output [1:0] dmem_htrans;
   output dmem_hmastlock;
   output [31:0] dmem_haddr;
   output dmem_hwrite;
   output [31:0] dmem_hwdata;
   input dmem_hready;
   input [31:0] dmem_hrdata;
   input dmem_hresp;

   // Internal wires
   wire \rcg_dmem_hwdata[0]_conNet ;
   wire \rcg_dmem_hwdata[1]_conNet ;
   wire \rcg_dmem_hwdata[2]_conNet ;
   wire \rcg_dmem_hwdata[3]_conNet ;
   wire \rcg_dmem_hwdata[4]_conNet ;
   wire \rcg_dmem_hwdata[5]_conNet ;
   wire \rcg_dmem_hwdata[6]_conNet ;
   wire \rcg_dmem_hwdata[7]_conNet ;
   wire \rcg_dmem_hwdata[8]_conNet ;
   wire \rcg_dmem_hwdata[9]_conNet ;
   wire \rcg_dmem_hwdata[10]_conNet ;
   wire \rcg_dmem_hwdata[11]_conNet ;
   wire \rcg_dmem_hwdata[12]_conNet ;
   wire \rcg_dmem_hwdata[13]_conNet ;
   wire \rcg_dmem_hwdata[14]_conNet ;
   wire \rcg_dmem_hwdata[15]_conNet ;
   wire \rcg_dmem_hwdata[16]_conNet ;
   wire \rcg_dmem_hwdata[17]_conNet ;
   wire \rcg_dmem_hwdata[18]_conNet ;
   wire \rcg_dmem_hwdata[19]_conNet ;
   wire \rcg_dmem_hwdata[20]_conNet ;
   wire \rcg_dmem_hwdata[21]_conNet ;
   wire \rcg_dmem_hwdata[22]_conNet ;
   wire \rcg_dmem_hwdata[23]_conNet ;
   wire \rcg_dmem_hwdata[24]_conNet ;
   wire \rcg_dmem_hwdata[25]_conNet ;
   wire \rcg_dmem_hwdata[26]_conNet ;
   wire \rcg_dmem_hwdata[27]_conNet ;
   wire \rcg_dmem_hwdata[28]_conNet ;
   wire \rcg_dmem_hwdata[29]_conNet ;
   wire \rcg_dmem_hwdata[30]_conNet ;
   wire \rcg_dmem_hwdata[31]_conNet ;
   wire rcg_dmem_hwrite_conNet;
   wire \rcg_dmem_haddr[0]_conNet ;
   wire \rcg_dmem_haddr[1]_conNet ;
   wire \rcg_dmem_haddr[2]_conNet ;
   wire \rcg_dmem_haddr[3]_conNet ;
   wire \rcg_dmem_haddr[4]_conNet ;
   wire \rcg_dmem_haddr[5]_conNet ;
   wire \rcg_dmem_haddr[6]_conNet ;
   wire \rcg_dmem_haddr[7]_conNet ;
   wire \rcg_dmem_haddr[8]_conNet ;
   wire \rcg_dmem_haddr[9]_conNet ;
   wire \rcg_dmem_haddr[10]_conNet ;
   wire \rcg_dmem_haddr[11]_conNet ;
   wire \rcg_dmem_haddr[12]_conNet ;
   wire \rcg_dmem_haddr[13]_conNet ;
   wire \rcg_dmem_haddr[14]_conNet ;
   wire \rcg_dmem_haddr[15]_conNet ;
   wire \rcg_dmem_haddr[16]_conNet ;
   wire \rcg_dmem_haddr[17]_conNet ;
   wire \rcg_dmem_haddr[18]_conNet ;
   wire \rcg_dmem_haddr[19]_conNet ;
   wire \rcg_dmem_haddr[20]_conNet ;
   wire \rcg_dmem_haddr[21]_conNet ;
   wire \rcg_dmem_haddr[22]_conNet ;
   wire \rcg_dmem_haddr[23]_conNet ;
   wire \rcg_dmem_haddr[24]_conNet ;
   wire \rcg_dmem_haddr[25]_conNet ;
   wire \rcg_dmem_haddr[26]_conNet ;
   wire \rcg_dmem_haddr[27]_conNet ;
   wire \rcg_dmem_haddr[28]_conNet ;
   wire \rcg_dmem_haddr[29]_conNet ;
   wire \rcg_dmem_haddr[30]_conNet ;
   wire \rcg_dmem_haddr[31]_conNet ;
   wire rcg_dmem_hmastlock_conNet;
   wire \rcg_dmem_htrans[0]_conNet ;
   wire \rcg_dmem_htrans[1]_conNet ;
   wire \rcg_dmem_hsize[0]_conNet ;
   wire \rcg_dmem_hsize[1]_conNet ;
   wire \rcg_dmem_hsize[2]_conNet ;
   wire \rcg_dmem_hburst[0]_conNet ;
   wire \rcg_dmem_hburst[1]_conNet ;
   wire \rcg_dmem_hburst[2]_conNet ;
   wire \rcg_dmem_hprot[0]_conNet ;
   wire \rcg_dmem_hprot[1]_conNet ;
   wire \rcg_dmem_hprot[2]_conNet ;
   wire \rcg_dmem_hprot[3]_conNet ;
   wire \rcg_imem_haddr[0]_conNet ;
   wire \rcg_imem_haddr[1]_conNet ;
   wire \rcg_imem_haddr[2]_conNet ;
   wire \rcg_imem_haddr[3]_conNet ;
   wire \rcg_imem_haddr[4]_conNet ;
   wire \rcg_imem_haddr[5]_conNet ;
   wire \rcg_imem_haddr[6]_conNet ;
   wire \rcg_imem_haddr[7]_conNet ;
   wire \rcg_imem_haddr[8]_conNet ;
   wire \rcg_imem_haddr[9]_conNet ;
   wire \rcg_imem_haddr[10]_conNet ;
   wire \rcg_imem_haddr[11]_conNet ;
   wire \rcg_imem_haddr[12]_conNet ;
   wire \rcg_imem_haddr[13]_conNet ;
   wire \rcg_imem_haddr[14]_conNet ;
   wire \rcg_imem_haddr[15]_conNet ;
   wire \rcg_imem_haddr[16]_conNet ;
   wire \rcg_imem_haddr[17]_conNet ;
   wire \rcg_imem_haddr[18]_conNet ;
   wire \rcg_imem_haddr[19]_conNet ;
   wire \rcg_imem_haddr[20]_conNet ;
   wire \rcg_imem_haddr[21]_conNet ;
   wire \rcg_imem_haddr[22]_conNet ;
   wire \rcg_imem_haddr[23]_conNet ;
   wire \rcg_imem_haddr[24]_conNet ;
   wire \rcg_imem_haddr[25]_conNet ;
   wire \rcg_imem_haddr[26]_conNet ;
   wire \rcg_imem_haddr[27]_conNet ;
   wire \rcg_imem_haddr[28]_conNet ;
   wire \rcg_imem_haddr[29]_conNet ;
   wire \rcg_imem_haddr[30]_conNet ;
   wire \rcg_imem_haddr[31]_conNet ;
   wire rcg_imem_hmastlock_conNet;
   wire \rcg_imem_htrans[0]_conNet ;
   wire \rcg_imem_htrans[1]_conNet ;
   wire \rcg_imem_hsize[0]_conNet ;
   wire \rcg_imem_hsize[1]_conNet ;
   wire \rcg_imem_hsize[2]_conNet ;
   wire \rcg_imem_hburst[0]_conNet ;
   wire \rcg_imem_hburst[1]_conNet ;
   wire \rcg_imem_hburst[2]_conNet ;
   wire \rcg_imem_hprot[0]_conNet ;
   wire \rcg_imem_hprot[1]_conNet ;
   wire \rcg_imem_hprot[2]_conNet ;
   wire \rcg_imem_hprot[3]_conNet ;
   wire rcg_soft_irq_conNet;
   wire rcg_ext_irq_conNet;
   wire rcg_dmem_hresp_conNet;
   wire \rcg_dmem_hrdata[0]_conNet ;
   wire \rcg_dmem_hrdata[1]_conNet ;
   wire \rcg_dmem_hrdata[2]_conNet ;
   wire \rcg_dmem_hrdata[3]_conNet ;
   wire \rcg_dmem_hrdata[4]_conNet ;
   wire \rcg_dmem_hrdata[5]_conNet ;
   wire \rcg_dmem_hrdata[6]_conNet ;
   wire \rcg_dmem_hrdata[7]_conNet ;
   wire \rcg_dmem_hrdata[8]_conNet ;
   wire \rcg_dmem_hrdata[9]_conNet ;
   wire \rcg_dmem_hrdata[10]_conNet ;
   wire \rcg_dmem_hrdata[11]_conNet ;
   wire \rcg_dmem_hrdata[12]_conNet ;
   wire \rcg_dmem_hrdata[13]_conNet ;
   wire \rcg_dmem_hrdata[14]_conNet ;
   wire \rcg_dmem_hrdata[15]_conNet ;
   wire \rcg_dmem_hrdata[16]_conNet ;
   wire \rcg_dmem_hrdata[17]_conNet ;
   wire \rcg_dmem_hrdata[18]_conNet ;
   wire \rcg_dmem_hrdata[19]_conNet ;
   wire \rcg_dmem_hrdata[20]_conNet ;
   wire \rcg_dmem_hrdata[21]_conNet ;
   wire \rcg_dmem_hrdata[22]_conNet ;
   wire \rcg_dmem_hrdata[23]_conNet ;
   wire \rcg_dmem_hrdata[24]_conNet ;
   wire \rcg_dmem_hrdata[25]_conNet ;
   wire \rcg_dmem_hrdata[26]_conNet ;
   wire \rcg_dmem_hrdata[27]_conNet ;
   wire \rcg_dmem_hrdata[28]_conNet ;
   wire \rcg_dmem_hrdata[29]_conNet ;
   wire \rcg_dmem_hrdata[30]_conNet ;
   wire \rcg_dmem_hrdata[31]_conNet ;
   wire rcg_dmem_hready_conNet;
   wire rcg_imem_hresp_conNet;
   wire \rcg_imem_hrdata[0]_conNet ;
   wire \rcg_imem_hrdata[1]_conNet ;
   wire \rcg_imem_hrdata[2]_conNet ;
   wire \rcg_imem_hrdata[3]_conNet ;
   wire \rcg_imem_hrdata[4]_conNet ;
   wire \rcg_imem_hrdata[5]_conNet ;
   wire \rcg_imem_hrdata[6]_conNet ;
   wire \rcg_imem_hrdata[7]_conNet ;
   wire \rcg_imem_hrdata[8]_conNet ;
   wire \rcg_imem_hrdata[9]_conNet ;
   wire \rcg_imem_hrdata[10]_conNet ;
   wire \rcg_imem_hrdata[11]_conNet ;
   wire \rcg_imem_hrdata[12]_conNet ;
   wire \rcg_imem_hrdata[13]_conNet ;
   wire \rcg_imem_hrdata[14]_conNet ;
   wire \rcg_imem_hrdata[15]_conNet ;
   wire \rcg_imem_hrdata[16]_conNet ;
   wire \rcg_imem_hrdata[17]_conNet ;
   wire \rcg_imem_hrdata[18]_conNet ;
   wire \rcg_imem_hrdata[19]_conNet ;
   wire \rcg_imem_hrdata[20]_conNet ;
   wire \rcg_imem_hrdata[21]_conNet ;
   wire \rcg_imem_hrdata[22]_conNet ;
   wire \rcg_imem_hrdata[23]_conNet ;
   wire \rcg_imem_hrdata[24]_conNet ;
   wire \rcg_imem_hrdata[25]_conNet ;
   wire \rcg_imem_hrdata[26]_conNet ;
   wire \rcg_imem_hrdata[27]_conNet ;
   wire \rcg_imem_hrdata[28]_conNet ;
   wire \rcg_imem_hrdata[29]_conNet ;
   wire \rcg_imem_hrdata[30]_conNet ;
   wire \rcg_imem_hrdata[31]_conNet ;
   wire rcg_imem_hready_conNet;
   wire rcg_rtc_clk_conNet;
   wire rcg_clk_conNet;
   wire rcg_test_rst_n_conNet;
   wire rcg_test_mode_conNet;
   wire rcg_cpu_rst_n_conNet;
   wire rcg_rst_n_conNet;
   wire rcg_pwrup_rst_n_conNet;
   wire [31:0] core_dmem_addr;
   wire core_dmem_wdata;
   wire core_dmem_req_ack;
   wire core_dmem_resp;
   wire clkout;

   PADVSS1 groundpad4 ();
   PADVSS1 groundpad3 ();
   PADVSS1 groundpad2 ();
   PADVSS1 groundpad1 ();
   PADVDD1 powerpad4 ();
   PADVDD1 powerpad3 ();
   PADVDD1 powerpad2 ();
   PADVDD1 powerpad1 ();
   PADCORNER corner4 ();
   PADCORNER corner3 ();
   PADCORNER corner2 ();
   PADCORNER corner1 ();
   PADO \pad_o_dmem_hwdata[0]  (.IN(\rcg_dmem_hwdata[0]_conNet ),
	.PAD(dmem_hwdata[0]));
   PADO \pad_o_dmem_hwdata[1]  (.IN(\rcg_dmem_hwdata[1]_conNet ),
	.PAD(dmem_hwdata[1]));
   PADO \pad_o_dmem_hwdata[2]  (.IN(\rcg_dmem_hwdata[2]_conNet ),
	.PAD(dmem_hwdata[2]));
   PADO \pad_o_dmem_hwdata[3]  (.IN(\rcg_dmem_hwdata[3]_conNet ),
	.PAD(dmem_hwdata[3]));
   PADO \pad_o_dmem_hwdata[4]  (.IN(\rcg_dmem_hwdata[4]_conNet ),
	.PAD(dmem_hwdata[4]));
   PADO \pad_o_dmem_hwdata[5]  (.IN(\rcg_dmem_hwdata[5]_conNet ),
	.PAD(dmem_hwdata[5]));
   PADO \pad_o_dmem_hwdata[6]  (.IN(\rcg_dmem_hwdata[6]_conNet ),
	.PAD(dmem_hwdata[6]));
   PADO \pad_o_dmem_hwdata[7]  (.IN(\rcg_dmem_hwdata[7]_conNet ),
	.PAD(dmem_hwdata[7]));
   PADO \pad_o_dmem_hwdata[8]  (.IN(\rcg_dmem_hwdata[8]_conNet ),
	.PAD(dmem_hwdata[8]));
   PADO \pad_o_dmem_hwdata[9]  (.IN(\rcg_dmem_hwdata[9]_conNet ),
	.PAD(dmem_hwdata[9]));
   PADO \pad_o_dmem_hwdata[10]  (.IN(\rcg_dmem_hwdata[10]_conNet ),
	.PAD(dmem_hwdata[10]));
   PADO \pad_o_dmem_hwdata[11]  (.IN(\rcg_dmem_hwdata[11]_conNet ),
	.PAD(dmem_hwdata[11]));
   PADO \pad_o_dmem_hwdata[12]  (.IN(\rcg_dmem_hwdata[12]_conNet ),
	.PAD(dmem_hwdata[12]));
   PADO \pad_o_dmem_hwdata[13]  (.IN(\rcg_dmem_hwdata[13]_conNet ),
	.PAD(dmem_hwdata[13]));
   PADO \pad_o_dmem_hwdata[14]  (.IN(\rcg_dmem_hwdata[14]_conNet ),
	.PAD(dmem_hwdata[14]));
   PADO \pad_o_dmem_hwdata[15]  (.IN(\rcg_dmem_hwdata[15]_conNet ),
	.PAD(dmem_hwdata[15]));
   PADO \pad_o_dmem_hwdata[16]  (.IN(\rcg_dmem_hwdata[16]_conNet ),
	.PAD(dmem_hwdata[16]));
   PADO \pad_o_dmem_hwdata[17]  (.IN(\rcg_dmem_hwdata[17]_conNet ),
	.PAD(dmem_hwdata[17]));
   PADO \pad_o_dmem_hwdata[18]  (.IN(\rcg_dmem_hwdata[18]_conNet ),
	.PAD(dmem_hwdata[18]));
   PADO \pad_o_dmem_hwdata[19]  (.IN(\rcg_dmem_hwdata[19]_conNet ),
	.PAD(dmem_hwdata[19]));
   PADO \pad_o_dmem_hwdata[20]  (.IN(\rcg_dmem_hwdata[20]_conNet ),
	.PAD(dmem_hwdata[20]));
   PADO \pad_o_dmem_hwdata[21]  (.IN(\rcg_dmem_hwdata[21]_conNet ),
	.PAD(dmem_hwdata[21]));
   PADO \pad_o_dmem_hwdata[22]  (.IN(\rcg_dmem_hwdata[22]_conNet ),
	.PAD(dmem_hwdata[22]));
   PADO \pad_o_dmem_hwdata[23]  (.IN(\rcg_dmem_hwdata[23]_conNet ),
	.PAD(dmem_hwdata[23]));
   PADO \pad_o_dmem_hwdata[24]  (.IN(\rcg_dmem_hwdata[24]_conNet ),
	.PAD(dmem_hwdata[24]));
   PADO \pad_o_dmem_hwdata[25]  (.IN(\rcg_dmem_hwdata[25]_conNet ),
	.PAD(dmem_hwdata[25]));
   PADO \pad_o_dmem_hwdata[26]  (.IN(\rcg_dmem_hwdata[26]_conNet ),
	.PAD(dmem_hwdata[26]));
   PADO \pad_o_dmem_hwdata[27]  (.IN(\rcg_dmem_hwdata[27]_conNet ),
	.PAD(dmem_hwdata[27]));
   PADO \pad_o_dmem_hwdata[28]  (.IN(\rcg_dmem_hwdata[28]_conNet ),
	.PAD(dmem_hwdata[28]));
   PADO \pad_o_dmem_hwdata[29]  (.IN(\rcg_dmem_hwdata[29]_conNet ),
	.PAD(dmem_hwdata[29]));
   PADO \pad_o_dmem_hwdata[30]  (.IN(\rcg_dmem_hwdata[30]_conNet ),
	.PAD(dmem_hwdata[30]));
   PADO \pad_o_dmem_hwdata[31]  (.IN(\rcg_dmem_hwdata[31]_conNet ),
	.PAD(dmem_hwdata[31]));
   PADO pad_o_dmem_hwrite (.IN(rcg_dmem_hwrite_conNet),
	.PAD(dmem_hwrite));
   PADO \pad_o_dmem_haddr[0]  (.IN(\rcg_dmem_haddr[0]_conNet ),
	.PAD(dmem_haddr[0]));
   PADO \pad_o_dmem_haddr[1]  (.IN(\rcg_dmem_haddr[1]_conNet ),
	.PAD(dmem_haddr[1]));
   PADO \pad_o_dmem_haddr[2]  (.IN(\rcg_dmem_haddr[2]_conNet ),
	.PAD(dmem_haddr[2]));
   PADO \pad_o_dmem_haddr[3]  (.IN(\rcg_dmem_haddr[3]_conNet ),
	.PAD(dmem_haddr[3]));
   PADO \pad_o_dmem_haddr[4]  (.IN(\rcg_dmem_haddr[4]_conNet ),
	.PAD(dmem_haddr[4]));
   PADO \pad_o_dmem_haddr[5]  (.IN(\rcg_dmem_haddr[5]_conNet ),
	.PAD(dmem_haddr[5]));
   PADO \pad_o_dmem_haddr[6]  (.IN(\rcg_dmem_haddr[6]_conNet ),
	.PAD(dmem_haddr[6]));
   PADO \pad_o_dmem_haddr[7]  (.IN(\rcg_dmem_haddr[7]_conNet ),
	.PAD(dmem_haddr[7]));
   PADO \pad_o_dmem_haddr[8]  (.IN(\rcg_dmem_haddr[8]_conNet ),
	.PAD(dmem_haddr[8]));
   PADO \pad_o_dmem_haddr[9]  (.IN(\rcg_dmem_haddr[9]_conNet ),
	.PAD(dmem_haddr[9]));
   PADO \pad_o_dmem_haddr[10]  (.IN(\rcg_dmem_haddr[10]_conNet ),
	.PAD(dmem_haddr[10]));
   PADO \pad_o_dmem_haddr[11]  (.IN(\rcg_dmem_haddr[11]_conNet ),
	.PAD(dmem_haddr[11]));
   PADO \pad_o_dmem_haddr[12]  (.IN(\rcg_dmem_haddr[12]_conNet ),
	.PAD(dmem_haddr[12]));
   PADO \pad_o_dmem_haddr[13]  (.IN(\rcg_dmem_haddr[13]_conNet ),
	.PAD(dmem_haddr[13]));
   PADO \pad_o_dmem_haddr[14]  (.IN(\rcg_dmem_haddr[14]_conNet ),
	.PAD(dmem_haddr[14]));
   PADO \pad_o_dmem_haddr[15]  (.IN(\rcg_dmem_haddr[15]_conNet ),
	.PAD(dmem_haddr[15]));
   PADO \pad_o_dmem_haddr[16]  (.IN(\rcg_dmem_haddr[16]_conNet ),
	.PAD(dmem_haddr[16]));
   PADO \pad_o_dmem_haddr[17]  (.IN(\rcg_dmem_haddr[17]_conNet ),
	.PAD(dmem_haddr[17]));
   PADO \pad_o_dmem_haddr[18]  (.IN(\rcg_dmem_haddr[18]_conNet ),
	.PAD(dmem_haddr[18]));
   PADO \pad_o_dmem_haddr[19]  (.IN(\rcg_dmem_haddr[19]_conNet ),
	.PAD(dmem_haddr[19]));
   PADO \pad_o_dmem_haddr[20]  (.IN(\rcg_dmem_haddr[20]_conNet ),
	.PAD(dmem_haddr[20]));
   PADO \pad_o_dmem_haddr[21]  (.IN(\rcg_dmem_haddr[21]_conNet ),
	.PAD(dmem_haddr[21]));
   PADO \pad_o_dmem_haddr[22]  (.IN(\rcg_dmem_haddr[22]_conNet ),
	.PAD(dmem_haddr[22]));
   PADO \pad_o_dmem_haddr[23]  (.IN(\rcg_dmem_haddr[23]_conNet ),
	.PAD(dmem_haddr[23]));
   PADO \pad_o_dmem_haddr[24]  (.IN(\rcg_dmem_haddr[24]_conNet ),
	.PAD(dmem_haddr[24]));
   PADO \pad_o_dmem_haddr[25]  (.IN(\rcg_dmem_haddr[25]_conNet ),
	.PAD(dmem_haddr[25]));
   PADO \pad_o_dmem_haddr[26]  (.IN(\rcg_dmem_haddr[26]_conNet ),
	.PAD(dmem_haddr[26]));
   PADO \pad_o_dmem_haddr[27]  (.IN(\rcg_dmem_haddr[27]_conNet ),
	.PAD(dmem_haddr[27]));
   PADO \pad_o_dmem_haddr[28]  (.IN(\rcg_dmem_haddr[28]_conNet ),
	.PAD(dmem_haddr[28]));
   PADO \pad_o_dmem_haddr[29]  (.IN(\rcg_dmem_haddr[29]_conNet ),
	.PAD(dmem_haddr[29]));
   PADO \pad_o_dmem_haddr[30]  (.IN(\rcg_dmem_haddr[30]_conNet ),
	.PAD(dmem_haddr[30]));
   PADO \pad_o_dmem_haddr[31]  (.IN(\rcg_dmem_haddr[31]_conNet ),
	.PAD(dmem_haddr[31]));
   PADO pad_o_dmem_hmastlock (.IN(rcg_dmem_hmastlock_conNet),
	.PAD(dmem_hmastlock));
   PADO \pad_o_dmem_htrans[0]  (.IN(\rcg_dmem_htrans[0]_conNet ),
	.PAD(dmem_htrans[0]));
   PADO \pad_o_dmem_htrans[1]  (.IN(\rcg_dmem_htrans[1]_conNet ),
	.PAD(dmem_htrans[1]));
   PADO \pad_o_dmem_hsize[0]  (.IN(\rcg_dmem_hsize[0]_conNet ),
	.PAD(dmem_hsize[0]));
   PADO \pad_o_dmem_hsize[1]  (.IN(\rcg_dmem_hsize[1]_conNet ),
	.PAD(dmem_hsize[1]));
   PADO \pad_o_dmem_hsize[2]  (.IN(\rcg_dmem_hsize[2]_conNet ),
	.PAD(dmem_hsize[2]));
   PADO \pad_o_dmem_hburst[0]  (.IN(\rcg_dmem_hburst[0]_conNet ),
	.PAD(dmem_hburst[0]));
   PADO \pad_o_dmem_hburst[1]  (.IN(\rcg_dmem_hburst[1]_conNet ),
	.PAD(dmem_hburst[1]));
   PADO \pad_o_dmem_hburst[2]  (.IN(\rcg_dmem_hburst[2]_conNet ),
	.PAD(dmem_hburst[2]));
   PADO \pad_o_dmem_hprot[0]  (.IN(\rcg_dmem_hprot[0]_conNet ),
	.PAD(dmem_hprot[0]));
   PADO \pad_o_dmem_hprot[1]  (.IN(\rcg_dmem_hprot[1]_conNet ),
	.PAD(dmem_hprot[1]));
   PADO \pad_o_dmem_hprot[2]  (.IN(\rcg_dmem_hprot[2]_conNet ),
	.PAD(dmem_hprot[2]));
   PADO \pad_o_dmem_hprot[3]  (.IN(\rcg_dmem_hprot[3]_conNet ),
	.PAD(dmem_hprot[3]));
   PADO \pad_o_imem_haddr[0]  (.IN(\rcg_imem_haddr[0]_conNet ),
	.PAD(imem_haddr[0]));
   PADO \pad_o_imem_haddr[1]  (.IN(\rcg_imem_haddr[1]_conNet ),
	.PAD(imem_haddr[1]));
   PADO \pad_o_imem_haddr[2]  (.IN(\rcg_imem_haddr[2]_conNet ),
	.PAD(imem_haddr[2]));
   PADO \pad_o_imem_haddr[3]  (.IN(\rcg_imem_haddr[3]_conNet ),
	.PAD(imem_haddr[3]));
   PADO \pad_o_imem_haddr[4]  (.IN(\rcg_imem_haddr[4]_conNet ),
	.PAD(imem_haddr[4]));
   PADO \pad_o_imem_haddr[5]  (.IN(\rcg_imem_haddr[5]_conNet ),
	.PAD(imem_haddr[5]));
   PADO \pad_o_imem_haddr[6]  (.IN(\rcg_imem_haddr[6]_conNet ),
	.PAD(imem_haddr[6]));
   PADO \pad_o_imem_haddr[7]  (.IN(\rcg_imem_haddr[7]_conNet ),
	.PAD(imem_haddr[7]));
   PADO \pad_o_imem_haddr[8]  (.IN(\rcg_imem_haddr[8]_conNet ),
	.PAD(imem_haddr[8]));
   PADO \pad_o_imem_haddr[9]  (.IN(\rcg_imem_haddr[9]_conNet ),
	.PAD(imem_haddr[9]));
   PADO \pad_o_imem_haddr[10]  (.IN(\rcg_imem_haddr[10]_conNet ),
	.PAD(imem_haddr[10]));
   PADO \pad_o_imem_haddr[11]  (.IN(\rcg_imem_haddr[11]_conNet ),
	.PAD(imem_haddr[11]));
   PADO \pad_o_imem_haddr[12]  (.IN(\rcg_imem_haddr[12]_conNet ),
	.PAD(imem_haddr[12]));
   PADO \pad_o_imem_haddr[13]  (.IN(\rcg_imem_haddr[13]_conNet ),
	.PAD(imem_haddr[13]));
   PADO \pad_o_imem_haddr[14]  (.IN(\rcg_imem_haddr[14]_conNet ),
	.PAD(imem_haddr[14]));
   PADO \pad_o_imem_haddr[15]  (.IN(\rcg_imem_haddr[15]_conNet ),
	.PAD(imem_haddr[15]));
   PADO \pad_o_imem_haddr[16]  (.IN(\rcg_imem_haddr[16]_conNet ),
	.PAD(imem_haddr[16]));
   PADO \pad_o_imem_haddr[17]  (.IN(\rcg_imem_haddr[17]_conNet ),
	.PAD(imem_haddr[17]));
   PADO \pad_o_imem_haddr[18]  (.IN(\rcg_imem_haddr[18]_conNet ),
	.PAD(imem_haddr[18]));
   PADO \pad_o_imem_haddr[19]  (.IN(\rcg_imem_haddr[19]_conNet ),
	.PAD(imem_haddr[19]));
   PADO \pad_o_imem_haddr[20]  (.IN(\rcg_imem_haddr[20]_conNet ),
	.PAD(imem_haddr[20]));
   PADO \pad_o_imem_haddr[21]  (.IN(\rcg_imem_haddr[21]_conNet ),
	.PAD(imem_haddr[21]));
   PADO \pad_o_imem_haddr[22]  (.IN(\rcg_imem_haddr[22]_conNet ),
	.PAD(imem_haddr[22]));
   PADO \pad_o_imem_haddr[23]  (.IN(\rcg_imem_haddr[23]_conNet ),
	.PAD(imem_haddr[23]));
   PADO \pad_o_imem_haddr[24]  (.IN(\rcg_imem_haddr[24]_conNet ),
	.PAD(imem_haddr[24]));
   PADO \pad_o_imem_haddr[25]  (.IN(\rcg_imem_haddr[25]_conNet ),
	.PAD(imem_haddr[25]));
   PADO \pad_o_imem_haddr[26]  (.IN(\rcg_imem_haddr[26]_conNet ),
	.PAD(imem_haddr[26]));
   PADO \pad_o_imem_haddr[27]  (.IN(\rcg_imem_haddr[27]_conNet ),
	.PAD(imem_haddr[27]));
   PADO \pad_o_imem_haddr[28]  (.IN(\rcg_imem_haddr[28]_conNet ),
	.PAD(imem_haddr[28]));
   PADO \pad_o_imem_haddr[29]  (.IN(\rcg_imem_haddr[29]_conNet ),
	.PAD(imem_haddr[29]));
   PADO \pad_o_imem_haddr[30]  (.IN(\rcg_imem_haddr[30]_conNet ),
	.PAD(imem_haddr[30]));
   PADO \pad_o_imem_haddr[31]  (.IN(\rcg_imem_haddr[31]_conNet ),
	.PAD(imem_haddr[31]));
   PADO pad_o_imem_hmastlock (.IN(rcg_imem_hmastlock_conNet),
	.PAD(imem_hmastlock));
   PADO \pad_o_imem_htrans[0]  (.IN(\rcg_imem_htrans[0]_conNet ),
	.PAD(imem_htrans[0]));
   PADO \pad_o_imem_htrans[1]  (.IN(\rcg_imem_htrans[1]_conNet ),
	.PAD(imem_htrans[1]));
   PADO \pad_o_imem_hsize[0]  (.IN(\rcg_imem_hsize[0]_conNet ),
	.PAD(imem_hsize[0]));
   PADO \pad_o_imem_hsize[1]  (.IN(\rcg_imem_hsize[1]_conNet ),
	.PAD(imem_hsize[1]));
   PADO \pad_o_imem_hsize[2]  (.IN(\rcg_imem_hsize[2]_conNet ),
	.PAD(imem_hsize[2]));
   PADO \pad_o_imem_hburst[0]  (.IN(\rcg_imem_hburst[0]_conNet ),
	.PAD(imem_hburst[0]));
   PADO \pad_o_imem_hburst[1]  (.IN(\rcg_imem_hburst[1]_conNet ),
	.PAD(imem_hburst[1]));
   PADO \pad_o_imem_hburst[2]  (.IN(\rcg_imem_hburst[2]_conNet ),
	.PAD(imem_hburst[2]));
   PADO \pad_o_imem_hprot[0]  (.IN(\rcg_imem_hprot[0]_conNet ),
	.PAD(imem_hprot[0]));
   PADO \pad_o_imem_hprot[1]  (.IN(\rcg_imem_hprot[1]_conNet ),
	.PAD(imem_hprot[1]));
   PADO \pad_o_imem_hprot[2]  (.IN(\rcg_imem_hprot[2]_conNet ),
	.PAD(imem_hprot[2]));
   PADO \pad_o_imem_hprot[3]  (.IN(\rcg_imem_hprot[3]_conNet ),
	.PAD(imem_hprot[3]));
   PADO pad_o_soft_irq (.IN(rcg_soft_irq_conNet),
	.PAD(soft_irq));
   PADO pad_o_ext_irq (.IN(rcg_ext_irq_conNet),
	.PAD(ext_irq));
   PADI pad_i_dmem_hresp (.PAD(dmem_hresp),
	.OUT(rcg_dmem_hresp_conNet));
   PADI \pad_i_dmem_hrdata[0]  (.PAD(dmem_hrdata[0]),
	.OUT(\rcg_dmem_hrdata[0]_conNet ));
   PADI \pad_i_dmem_hrdata[1]  (.PAD(dmem_hrdata[1]),
	.OUT(\rcg_dmem_hrdata[1]_conNet ));
   PADI \pad_i_dmem_hrdata[2]  (.PAD(dmem_hrdata[2]),
	.OUT(\rcg_dmem_hrdata[2]_conNet ));
   PADI \pad_i_dmem_hrdata[3]  (.PAD(dmem_hrdata[3]),
	.OUT(\rcg_dmem_hrdata[3]_conNet ));
   PADI \pad_i_dmem_hrdata[4]  (.PAD(dmem_hrdata[4]),
	.OUT(\rcg_dmem_hrdata[4]_conNet ));
   PADI \pad_i_dmem_hrdata[5]  (.PAD(dmem_hrdata[5]),
	.OUT(\rcg_dmem_hrdata[5]_conNet ));
   PADI \pad_i_dmem_hrdata[6]  (.PAD(dmem_hrdata[6]),
	.OUT(\rcg_dmem_hrdata[6]_conNet ));
   PADI \pad_i_dmem_hrdata[7]  (.PAD(dmem_hrdata[7]),
	.OUT(\rcg_dmem_hrdata[7]_conNet ));
   PADI \pad_i_dmem_hrdata[8]  (.PAD(dmem_hrdata[8]),
	.OUT(\rcg_dmem_hrdata[8]_conNet ));
   PADI \pad_i_dmem_hrdata[9]  (.PAD(dmem_hrdata[9]),
	.OUT(\rcg_dmem_hrdata[9]_conNet ));
   PADI \pad_i_dmem_hrdata[10]  (.PAD(dmem_hrdata[10]),
	.OUT(\rcg_dmem_hrdata[10]_conNet ));
   PADI \pad_i_dmem_hrdata[11]  (.PAD(dmem_hrdata[11]),
	.OUT(\rcg_dmem_hrdata[11]_conNet ));
   PADI \pad_i_dmem_hrdata[12]  (.PAD(dmem_hrdata[12]),
	.OUT(\rcg_dmem_hrdata[12]_conNet ));
   PADI \pad_i_dmem_hrdata[13]  (.PAD(dmem_hrdata[13]),
	.OUT(\rcg_dmem_hrdata[13]_conNet ));
   PADI \pad_i_dmem_hrdata[14]  (.PAD(dmem_hrdata[14]),
	.OUT(\rcg_dmem_hrdata[14]_conNet ));
   PADI \pad_i_dmem_hrdata[15]  (.PAD(dmem_hrdata[15]),
	.OUT(\rcg_dmem_hrdata[15]_conNet ));
   PADI \pad_i_dmem_hrdata[16]  (.PAD(dmem_hrdata[16]),
	.OUT(\rcg_dmem_hrdata[16]_conNet ));
   PADI \pad_i_dmem_hrdata[17]  (.PAD(dmem_hrdata[17]),
	.OUT(\rcg_dmem_hrdata[17]_conNet ));
   PADI \pad_i_dmem_hrdata[18]  (.PAD(dmem_hrdata[18]),
	.OUT(\rcg_dmem_hrdata[18]_conNet ));
   PADI \pad_i_dmem_hrdata[19]  (.PAD(dmem_hrdata[19]),
	.OUT(\rcg_dmem_hrdata[19]_conNet ));
   PADI \pad_i_dmem_hrdata[20]  (.PAD(dmem_hrdata[20]),
	.OUT(\rcg_dmem_hrdata[20]_conNet ));
   PADI \pad_i_dmem_hrdata[21]  (.PAD(dmem_hrdata[21]),
	.OUT(\rcg_dmem_hrdata[21]_conNet ));
   PADI \pad_i_dmem_hrdata[22]  (.PAD(dmem_hrdata[22]),
	.OUT(\rcg_dmem_hrdata[22]_conNet ));
   PADI \pad_i_dmem_hrdata[23]  (.PAD(dmem_hrdata[23]),
	.OUT(\rcg_dmem_hrdata[23]_conNet ));
   PADI \pad_i_dmem_hrdata[24]  (.PAD(dmem_hrdata[24]),
	.OUT(\rcg_dmem_hrdata[24]_conNet ));
   PADI \pad_i_dmem_hrdata[25]  (.PAD(dmem_hrdata[25]),
	.OUT(\rcg_dmem_hrdata[25]_conNet ));
   PADI \pad_i_dmem_hrdata[26]  (.PAD(dmem_hrdata[26]),
	.OUT(\rcg_dmem_hrdata[26]_conNet ));
   PADI \pad_i_dmem_hrdata[27]  (.PAD(dmem_hrdata[27]),
	.OUT(\rcg_dmem_hrdata[27]_conNet ));
   PADI \pad_i_dmem_hrdata[28]  (.PAD(dmem_hrdata[28]),
	.OUT(\rcg_dmem_hrdata[28]_conNet ));
   PADI \pad_i_dmem_hrdata[29]  (.PAD(dmem_hrdata[29]),
	.OUT(\rcg_dmem_hrdata[29]_conNet ));
   PADI \pad_i_dmem_hrdata[30]  (.PAD(dmem_hrdata[30]),
	.OUT(\rcg_dmem_hrdata[30]_conNet ));
   PADI \pad_i_dmem_hrdata[31]  (.PAD(dmem_hrdata[31]),
	.OUT(\rcg_dmem_hrdata[31]_conNet ));
   PADI pad_i_dmem_hready (.PAD(dmem_hready),
	.OUT(rcg_dmem_hready_conNet));
   PADI pad_i_imem_hresp (.PAD(imem_hresp),
	.OUT(rcg_imem_hresp_conNet));
   PADI \pad_i_imem_hrdata[0]  (.PAD(imem_hrdata[0]),
	.OUT(\rcg_imem_hrdata[0]_conNet ));
   PADI \pad_i_imem_hrdata[1]  (.PAD(imem_hrdata[1]),
	.OUT(\rcg_imem_hrdata[1]_conNet ));
   PADI \pad_i_imem_hrdata[2]  (.PAD(imem_hrdata[2]),
	.OUT(\rcg_imem_hrdata[2]_conNet ));
   PADI \pad_i_imem_hrdata[3]  (.PAD(imem_hrdata[3]),
	.OUT(\rcg_imem_hrdata[3]_conNet ));
   PADI \pad_i_imem_hrdata[4]  (.PAD(imem_hrdata[4]),
	.OUT(\rcg_imem_hrdata[4]_conNet ));
   PADI \pad_i_imem_hrdata[5]  (.PAD(imem_hrdata[5]),
	.OUT(\rcg_imem_hrdata[5]_conNet ));
   PADI \pad_i_imem_hrdata[6]  (.PAD(imem_hrdata[6]),
	.OUT(\rcg_imem_hrdata[6]_conNet ));
   PADI \pad_i_imem_hrdata[7]  (.PAD(imem_hrdata[7]),
	.OUT(\rcg_imem_hrdata[7]_conNet ));
   PADI \pad_i_imem_hrdata[8]  (.PAD(imem_hrdata[8]),
	.OUT(\rcg_imem_hrdata[8]_conNet ));
   PADI \pad_i_imem_hrdata[9]  (.PAD(imem_hrdata[9]),
	.OUT(\rcg_imem_hrdata[9]_conNet ));
   PADI \pad_i_imem_hrdata[10]  (.PAD(imem_hrdata[10]),
	.OUT(\rcg_imem_hrdata[10]_conNet ));
   PADI \pad_i_imem_hrdata[11]  (.PAD(imem_hrdata[11]),
	.OUT(\rcg_imem_hrdata[11]_conNet ));
   PADI \pad_i_imem_hrdata[12]  (.PAD(imem_hrdata[12]),
	.OUT(\rcg_imem_hrdata[12]_conNet ));
   PADI \pad_i_imem_hrdata[13]  (.PAD(imem_hrdata[13]),
	.OUT(\rcg_imem_hrdata[13]_conNet ));
   PADI \pad_i_imem_hrdata[14]  (.PAD(imem_hrdata[14]),
	.OUT(\rcg_imem_hrdata[14]_conNet ));
   PADI \pad_i_imem_hrdata[15]  (.PAD(imem_hrdata[15]),
	.OUT(\rcg_imem_hrdata[15]_conNet ));
   PADI \pad_i_imem_hrdata[16]  (.PAD(imem_hrdata[16]),
	.OUT(\rcg_imem_hrdata[16]_conNet ));
   PADI \pad_i_imem_hrdata[17]  (.PAD(imem_hrdata[17]),
	.OUT(\rcg_imem_hrdata[17]_conNet ));
   PADI \pad_i_imem_hrdata[18]  (.PAD(imem_hrdata[18]),
	.OUT(\rcg_imem_hrdata[18]_conNet ));
   PADI \pad_i_imem_hrdata[19]  (.PAD(imem_hrdata[19]),
	.OUT(\rcg_imem_hrdata[19]_conNet ));
   PADI \pad_i_imem_hrdata[20]  (.PAD(imem_hrdata[20]),
	.OUT(\rcg_imem_hrdata[20]_conNet ));
   PADI \pad_i_imem_hrdata[21]  (.PAD(imem_hrdata[21]),
	.OUT(\rcg_imem_hrdata[21]_conNet ));
   PADI \pad_i_imem_hrdata[22]  (.PAD(imem_hrdata[22]),
	.OUT(\rcg_imem_hrdata[22]_conNet ));
   PADI \pad_i_imem_hrdata[23]  (.PAD(imem_hrdata[23]),
	.OUT(\rcg_imem_hrdata[23]_conNet ));
   PADI \pad_i_imem_hrdata[24]  (.PAD(imem_hrdata[24]),
	.OUT(\rcg_imem_hrdata[24]_conNet ));
   PADI \pad_i_imem_hrdata[25]  (.PAD(imem_hrdata[25]),
	.OUT(\rcg_imem_hrdata[25]_conNet ));
   PADI \pad_i_imem_hrdata[26]  (.PAD(imem_hrdata[26]),
	.OUT(\rcg_imem_hrdata[26]_conNet ));
   PADI \pad_i_imem_hrdata[27]  (.PAD(imem_hrdata[27]),
	.OUT(\rcg_imem_hrdata[27]_conNet ));
   PADI \pad_i_imem_hrdata[28]  (.PAD(imem_hrdata[28]),
	.OUT(\rcg_imem_hrdata[28]_conNet ));
   PADI \pad_i_imem_hrdata[29]  (.PAD(imem_hrdata[29]),
	.OUT(\rcg_imem_hrdata[29]_conNet ));
   PADI \pad_i_imem_hrdata[30]  (.PAD(imem_hrdata[30]),
	.OUT(\rcg_imem_hrdata[30]_conNet ));
   PADI \pad_i_imem_hrdata[31]  (.PAD(imem_hrdata[31]),
	.OUT(\rcg_imem_hrdata[31]_conNet ));
   PADI pad_i_imem_hready (.PAD(imem_hready),
	.OUT(rcg_imem_hready_conNet));
   PADI pad_i_rtc_clk (.PAD(rtc_clk),
	.OUT(rcg_rtc_clk_conNet));
   PADI pad_i_clk (.PAD(clk),
	.OUT(rcg_clk_conNet));
   PADI pad_i_test_rst_n (.PAD(test_rst_n),
	.OUT(rcg_test_rst_n_conNet));
   PADI pad_i_test_mode (.PAD(test_mode),
	.OUT(rcg_test_mode_conNet));
   PADI pad_i_cpu_rst_n (.PAD(cpu_rst_n),
	.OUT(rcg_cpu_rst_n_conNet));
   PADI pad_i_rst_n (.PAD(rst_n),
	.OUT(rcg_rst_n_conNet));
   PADI pad_i_pwrup_rst_n (.PAD(pwrup_rst_n),
	.OUT(rcg_pwrup_rst_n_conNet));
   scr1_pipe_top i_pipe_top (.clkout(clkout),
	.soc2pipe_fuse_mhartid_i(dmem_hrdata),
	.soc2pipe_mtimer_val_i({ 1'b0,
		1'b0,
		1'b0,
		1'b0,
		1'b0,
		1'b0,
		1'b0,
		1'b0,
		1'b0,
		1'b0,
		1'b0,
		1'b0,
		1'b0,
		1'b0,
		1'b0,
		1'b0,
		1'b0,
		1'b0,
		1'b0,
		1'b0,
		1'b0,
		1'b0,
		1'b0,
		1'b0,
		1'b0,
		1'b0,
		1'b0,
		1'b0,
		1'b0,
		1'b0,
		1'b0,
		1'b0,
		1'b0,
		1'b0,
		1'b0,
		1'b0,
		1'b0,
		1'b0,
		1'b0,
		1'b0,
		1'b0,
		1'b0,
		1'b0,
		1'b0,
		1'b0,
		1'b0,
		1'b0,
		1'b0,
		1'b0,
		1'b0,
		1'b0,
		1'b0,
		1'b0,
		1'b0,
		1'b0,
		1'b0,
		1'b0,
		1'b0,
		1'b0,
		1'b0,
		1'b0,
		1'b0,
		1'b0,
		1'b0 }),
	.soc2pipe_irq_mtimer_i(dmem_hready),
	.soc2pipe_irq_soft_i(test_mode),
	.soc2pipe_irq_ext_i(imem_hready),
	.dmem2pipe_resp_i({ FE_UNCONNECTEDZ_0,
		core_dmem_resp }),
	.dmem2pipe_rdata_i(imem_hrdata),
	.dmem2pipe_req_ack_i(core_dmem_req_ack),
	.pipe2dmem_wdata_o({ FE_UNCONNECTEDZ_1,
		FE_UNCONNECTEDZ_2,
		FE_UNCONNECTEDZ_3,
		FE_UNCONNECTEDZ_4,
		FE_UNCONNECTEDZ_5,
		FE_UNCONNECTEDZ_6,
		FE_UNCONNECTEDZ_7,
		FE_UNCONNECTEDZ_8,
		FE_UNCONNECTEDZ_9,
		FE_UNCONNECTEDZ_10,
		FE_UNCONNECTEDZ_11,
		FE_UNCONNECTEDZ_12,
		FE_UNCONNECTEDZ_13,
		FE_UNCONNECTEDZ_14,
		FE_UNCONNECTEDZ_15,
		FE_UNCONNECTEDZ_16,
		FE_UNCONNECTEDZ_17,
		FE_UNCONNECTEDZ_18,
		FE_UNCONNECTEDZ_19,
		FE_UNCONNECTEDZ_20,
		FE_UNCONNECTEDZ_21,
		FE_UNCONNECTEDZ_22,
		FE_UNCONNECTEDZ_23,
		FE_UNCONNECTEDZ_24,
		FE_UNCONNECTEDZ_25,
		FE_UNCONNECTEDZ_26,
		FE_UNCONNECTEDZ_27,
		FE_UNCONNECTEDZ_28,
		FE_UNCONNECTEDZ_29,
		FE_UNCONNECTEDZ_30,
		FE_UNCONNECTEDZ_31,
		core_dmem_wdata }),
	.pipe2dmem_addr_o(core_dmem_addr),
	.pipe2dmem_width_o(imem_htrans),
	.pipe2dmem_cmd_o(ext_irq),
	.pipe2dmem_req_o(soft_irq),
	.imem2pipe_resp_i({ FE_UNCONNECTEDZ_32,
		dmem_hresp }),
	.imem2pipe_rdata_i(dmem_hrdata),
	.imem2pipe_req_ack_i(imem_hresp),
	.pipe2imem_addr_o(dmem_haddr),
	.pipe2imem_cmd_o(dmem_hwrite),
	.pipe2imem_req_o(dmem_hmastlock),
	.clk(clk),
	.pipe_rst_n(cpu_rst_n));
   sram_32_1024_scl180 sram_32_1024_scl180 (.din0({ FE_UNCONNECTEDZ_33,
		FE_UNCONNECTEDZ_34,
		FE_UNCONNECTEDZ_35,
		FE_UNCONNECTEDZ_36,
		FE_UNCONNECTEDZ_37,
		FE_UNCONNECTEDZ_38,
		FE_UNCONNECTEDZ_39,
		FE_UNCONNECTEDZ_40,
		FE_UNCONNECTEDZ_41,
		FE_UNCONNECTEDZ_42,
		FE_UNCONNECTEDZ_43,
		FE_UNCONNECTEDZ_44,
		FE_UNCONNECTEDZ_45,
		FE_UNCONNECTEDZ_46,
		FE_UNCONNECTEDZ_47,
		FE_UNCONNECTEDZ_48,
		FE_UNCONNECTEDZ_49,
		FE_UNCONNECTEDZ_50,
		FE_UNCONNECTEDZ_51,
		FE_UNCONNECTEDZ_52,
		FE_UNCONNECTEDZ_53,
		FE_UNCONNECTEDZ_54,
		FE_UNCONNECTEDZ_55,
		FE_UNCONNECTEDZ_56,
		FE_UNCONNECTEDZ_57,
		FE_UNCONNECTEDZ_58,
		FE_UNCONNECTEDZ_59,
		FE_UNCONNECTEDZ_60,
		FE_UNCONNECTEDZ_61,
		FE_UNCONNECTEDZ_62,
		FE_UNCONNECTEDZ_63,
		core_dmem_wdata }),
	.dout0(dmem_hwdata),
	.addr0({ core_dmem_addr[9],
		core_dmem_addr[8],
		core_dmem_addr[7],
		core_dmem_addr[6],
		core_dmem_addr[5],
		core_dmem_addr[4],
		core_dmem_addr[3],
		core_dmem_addr[2],
		core_dmem_addr[1],
		core_dmem_addr[0] }),
	.csb0(pwrup_rst_n),
	.web0(dmem_hready),
	.clk0(clkout));
endmodule

